SDK-441
incountry/sdk-csharp pull request #106
Opened 2021-09-07 09:23 UTC by VladimirLevitskiy

Work relates to:
----------------
Link(s) to Jira Task/User Story/Bug/Epic (if any):
- [SDK-441](https://incountry.atlassian.net/browse/SDK-441)

Code Quality (Before submitting PR)
------------
- [ ] Ensure code compiles and passes Sonar Lint.
- [ ] Do your best to ensure integration tests pass. If they don't then...
- [ ] Remove, ignore, or mark pending any brittle tests.
- [ ] Remove commented out code.

Target Release
--------------
- [ ] Please put the target release vehicle this needs to be bundled with.
- [ ] Did you increment the version? What is the new version?

2021-09-07 12:18 UTC, RommeroInCountry requested changes

2021-09-07 12:18 UTC, RommeroInCountry commented on README.md
> +By setting the `NormalizeKeys` option to `true`, you can store all string keys of any record as lowercase (except `Body` and `PrecommitBody`).
the idea is that SDK changes keys to be stored in lower case. The new wording heavily changes the meaning.

2021-09-07 12:18 UTC, RommeroInCountry commented on README.md
> +By setting the `NormalizeKeys` option to `true`, you can store all string keys of any record as lowercase (except `Body` and `PrecommitBody`).
By setting the `NormalizeKeys` option to `true` all the string keys of any record will be stored in lower case

2021-09-07 12:18 UTC, RommeroInCountry commented on README.md
> +// This method returns a record with normalized string keys (converted to lowercase)
The method

2021-09-07 12:18 UTC, RommeroInCountry commented on README.md
> +By setting the `HashSearchKeys` option to `false`, you can store the `Key1-Key20` record fields as unhashed, which enables the partial match search (see [Partial text match search](#partial-text-matc
you can store the `Key1-Key20` record fields unhashed.
"as" is kinda too much here

2021-09-07 12:18 UTC, RommeroInCountry commented on README.md
> +You can use the `FindResult.Errors` attribute to get the list of the `RecordException` objects that also contains detailed information about records that were not processed correctly during the execu
no need for "also" as we don't go into more details here. Neither we describe these entities previously.

2021-09-07 12:18 UTC, RommeroInCountry commented on README.md
> +You can use the `DeleteAsync` method to delete single records from the InCountry platform by their `RecordKey` field.
to delete a single record ... by its

2021-09-07 12:18 UTC, RommeroInCountry commented on README.md
> +You can use `BatchDeleteAsync` method to delete multiple records from the InCountry platform. As of now, the SDK supports the deletion of records only by providing a list of the `RecordKey` values (p
The idea is exactly "For now". As of now has some deeper meanings that may introduce some ambiguation here

2021-09-07 12:18 UTC, RommeroInCountry commented on README.md
> +You can use `BatchDeleteAsync` method to delete multiple records from the InCountry platform. As of now, the SDK supports the deletion of records only by providing a list of the `RecordKey` values (p
Why not "via `FindFilter` instance"? It's commonly used in tech docs

2021-09-07 12:18 UTC, RommeroInCountry commented on README.md
> +The C# SDK supports the usage of any 32-byte (256-bit) AES key, including the ones produced with an AWS KMS symmetric master key (CMK).
by is fine here

2021-09-07 12:18 UTC, RommeroInCountry commented on README.md
> +If none of the custom implementations of the `AbstractCipher` constructor are defined, the SDK will use the default encryption method to encrypt stored data. At the same time, it will keep the abilit
`AbstractCipher` constructor -> `AbstractCipher`

2021-09-07 14:03 UTC, vadim-rutkevich-incountry commented on README.md
> +    /// Login (Client ID) for OAuth authorization. It can be also set through INC_CLIENT_ID environment variable
Ok. fixed. via = through.

2021-09-07 14:03 UTC, vadim-rutkevich-incountry commented on README.md
> +    /// It can be also set through the INC_CLIENT_SECRET environment variable
Ok. fixed. via = through.

2021-09-07 14:04 UTC, vadim-rutkevich-incountry commented on README.md
> +    /// A custom endpoint for loading the countries list. This parameter is optional
Unified with the rest.

2021-09-07 14:05 UTC, vadim-rutkevich-incountry commented on README.md
> +    /// HTTP requests timeout. This parameter is optional. It should be greater than 0.
Unified with the rest.

2021-09-07 14:05 UTC, vadim-rutkevich-incountry commented on README.md
> +You can use the `FindResult.Errors` attribute to get the list of the `RecordException` objects that also contains detailed information about records that were not processed correctly during the execu
ok. removed.

2021-09-07 14:06 UTC, vadim-rutkevich-incountry commented on README.md
> +You can use the `DeleteAsync` method to delete single records from the InCountry platform by their `RecordKey` field.
ok. unified.

2021-09-07 14:07 UTC, vadim-rutkevich-incountry commented on README.md
> +You can use `BatchDeleteAsync` method to delete multiple records from the InCountry platform. As of now, the SDK supports the deletion of records only by providing a list of the `RecordKey` values (p
corrected according to your comments

2021-09-07 14:08 UTC, vadim-rutkevich-incountry commented on README.md
> +The C# SDK supports the usage of any 32-byte (256-bit) AES key, including the ones produced with an AWS KMS symmetric master key (CMK).
returned by.

2021-09-07 14:09 UTC, vadim-rutkevich-incountry commented on README.md
> +If none of the custom implementations of the `AbstractCipher` constructor are defined, the SDK will use the default encryption method to encrypt stored data. At the same time, it will keep the abilit
removed.

2021-09-07 14:10 UTC, vadim-rutkevich-incountry commented on README.md
> +    /// The regional dictionary with custom endpoints to fetch OAuth tokens.
corrected.

2021-09-07 14:11 UTC, vadim-rutkevich-incountry commented on README.md
> +    /// It can be used only with {@link #setDefaultAuthEndpoint(String)}
Corrected

2021-09-07 14:11 UTC, vadim-rutkevich-incountry commented on README.md
> +    /// This parameter is optional
Corrected.

2021-09-07 14:12 UTC, vadim-rutkevich-incountry commented on README.md
> +    /// The valid format: key = region, value = authorization server URL for a specific region.
@RommeroInCountry which one? dictionary or format?

2021-09-07 14:13 UTC, vadim-rutkevich-incountry commented on README.md
> +    /// It cannot be null when the <see cref="AuthEndpoints"/> parameter is used
corrected.

2021-09-07 14:16 UTC, vadim-rutkevich-incountry commented on README.md
> +    /// If true, all keys will be stored as lowercase. By default, it is set as false
ok, corrected.

2021-09-07 14:16 UTC, vadim-rutkevich-incountry commented on README.md
> +    /// The function to fetch an encryption secret.
fixed.

2021-09-07 14:17 UTC, vadim-rutkevich-incountry commented on README.md
> +    /// If null, regulated data will be stored without Base64 encryption
Corrected

2021-09-07 14:18 UTC, vadim-rutkevich-incountry commented on README.md
> +    /// It allows you to register custom ciphers for encrypting stored data.
Removed it.

2021-09-07 14:19 UTC, vadim-rutkevich-incountry commented on README.md
> +    /// Optional. It is used to acquire an OAuth2 token.
Used to provide/acquire an OAuth2 token. changed for this.

2021-09-07 14:19 UTC, vadim-rutkevich-incountry commented on README.md
> +    /// Optional. It sets a custom initial retry delay in seconds.
fixed.

2021-09-07 14:20 UTC, vadim-rutkevich-incountry commented on README.md
> +    /// If null,  - default 1 second delay will be used
If set as null, the default 1-second delay is used
Fixed this during review.

2021-09-07 14:22 UTC, vadim-rutkevich-incountry commented on README.md
> +The SDK allows you to precisely configure OAuth authorization endpoints if needed. Use this option only if your configuration plan requires this.
ok let it be so.

2021-09-07 14:22 UTC, vadim-rutkevich-incountry commented on README.md
> +You can also use the `SecretsDataGenerator` class to create instances of the `SecretsData` object:
fixed.

2021-09-07 14:23 UTC, vadim-rutkevich-incountry commented on README.md
> +The SDK encrypts data with the current secret/key while maintaining the ability to decrypt records encrypted with prior versions of the key/secret. The SDK also provides a method to migrate data that
replaced.

2021-09-07 14:24 UTC, vadim-rutkevich-incountry commented on README.md
> +By setting the `NormalizeKeys` option to `true`, you can store all string keys of any record as lowercase (except `Body` and `PrecommitBody`).
Corrected.

2021-09-07 14:25 UTC, vadim-rutkevich-incountry commented on README.md
> +// This method returns a record with normalized string keys (converted to lowercase)
fixed

2021-09-07 14:25 UTC, vadim-rutkevich-incountry commented on README.md
> +By setting the `HashSearchKeys` option to `false`, you can store the `Key1-Key20` record fields as unhashed, which enables the partial match search (see [Partial text match search](#partial-text-matc
removed.

2021-09-07 15:34 UTC, vadim-rutkevich-incountry commented on README.md
> +    * [Configuration of OAuth options](#configuration-of-oauth-options)
Section was renamed.

2021-09-08 12:17 UTC, RommeroInCountry approved these changes

2021-09-08 12:17 UTC, RommeroInCountry commented on README.md
> +    /// The valid format: key = region, value = authorization server URL for a specific region.
The valid format -> valid format

2021-09-08 12:17 UTC, RommeroInCountry commented on README.md
> +You can see an implementation example of a custom encryption method (using Fernet encryption from https://github.com/thangchung/fernet-dotnet) at [this resource](/UnitTests/crypto/cipher/FernetCipher
method is not the right word here. It kinda confuses everything here because custom encryption is not just a single method.  I'd remove it here (and above as well)

2021-09-08 12:17 UTC, RommeroInCountry commented on README.md
> +If none of the custom implementations of `AbstractCipher` are defined, the SDK will use the default encryption method to encrypt stored data. At the same time, it will keep the ability to decrypt old
default encryption method -> default encryption 
custom encryption method -> custom encryption

2021-09-08 12:32 UTC, vadim-rutkevich-incountry commented on README.md
> +If none of the custom implementations of `AbstractCipher` are defined, the SDK will use the default encryption method to encrypt stored data. At the same time, it will keep the ability to decrypt old
fixed

2021-09-08 12:32 UTC, vadim-rutkevich-incountry commented on README.md
> +You can see an implementation example of a custom encryption method (using Fernet encryption from https://github.com/thangchung/fernet-dotnet) at [this resource](/UnitTests/crypto/cipher/FernetCipher
fixed

2021-09-08 12:34 UTC, RommeroInCountry approved these changes

2021-09-08 12:37 UTC, vadim-rutkevich-incountry submitted a review, later dismissed
Looks fine. let's merge into 4.2.0.

2021-09-08 13:03 UTC, vadim-rutkevich-incountry approved these changes
Looks ok to me.

2021-09-08 13:10 UTC, RommeroInCountry approved these changes

2021-09-08 13:16 UTC, merged