SDK-455 [C# SDK] Add support for enhanced search
incountry/sdk-csharp pull request #111
Opened 2021-10-25 07:10 UTC by VladimirLevitskiy

Work relates to:
----------------
Link(s) to Jira Task/User Story/Bug/Epic (if any):
- [SDK-455](https://incountry.atlassian.net/browse/SDK-455)

Code Quality (Before submitting PR)
------------
- [x] Ensure code compiles and passes Sonar Lint.
- [x] Do your best to ensure integration tests pass. If they don't then...
- [x] Remove, ignore, or mark pending any brittle tests.
- [x] Remove commented out code.

Target Release
--------------
- [ ] Please put the target release vehicle this needs to be bundled with.
- [ ] Did you increment the version? What is the new version?

2021-11-30 13:53 UTC, RommeroInCountry requested changes

2021-11-30 13:53 UTC, RommeroInCountry commented on InCountrySDK/Resources.resx
> +    <value>Filters count must be >= 2</value>
At least 2 filters required for OrCondition

2021-11-30 13:53 UTC, RommeroInCountry commented on InCountrySDK/Resources.resx
> +    <value>SearchKeys filter combining with OR condition is not supported</value>
SearchKeys filter is incompatible with OR condition filter

2021-11-30 13:53 UTC, RommeroInCountry commented on InCountrySDK/StorageConfig.cs
> +        /// <exception cref="Exception.StorageClientException">When incompatible options combination were set</exception>
In case of invalid configuration / When selected configuration options are not compatible with each other

2021-11-30 13:53 UTC, RommeroInCountry commented on README.md
> +For adding logical `OR` filter you can use `orCondition` of `FindFilter` class.
To use logical `OR` condition in your find request you can use `orCondition` method of `FindFilter` class.

2021-11-30 13:53 UTC, RommeroInCountry commented on README.md
> +    KEY1='JOHN SMITH')
please make the example more accurate. The values above (in java code) are CamelCase while SQL has all Johns and Smiths in uppercase

2021-11-30 13:53 UTC, RommeroInCountry commented on README.md
> +The current SDK version provides only one top-level OR filter condition.
OR filter condition -> OR condition filter

2021-12-13 14:28 UTC, RommeroInCountry approved these changes

2021-12-15 18:37 UTC, robert-par approved these changes

2021-12-16 10:42 UTC, merged