SDK-531
incountry/sdk-csharp pull request #127
Opened 2022-03-09 19:12 UTC by VladimirLevitskiy

…class now can be extended

Work relates to:
----------------
Link(s) to Jira Task/User Story/Bug/Epic (if any):
- [SDK-531](https://incountry.atlassian.net/browse/SDK-531)

Code Quality (Before submitting PR)
------------
- [ ] Ensure code compiles and passes Sonar Lint.
- [ ] Do your best to ensure integration tests pass. If they don't then...
- [ ] Remove, ignore, or mark pending any brittle tests.
- [ ] Remove commented out code.

Target Release
--------------
- [ ] Please put the target release vehicle this needs to be bundled with.
- [ ] Did you increment the version? What is the new version?

2022-03-10 13:42 UTC, RommeroInCountry requested changes

2022-03-10 13:42 UTC, RommeroInCountry commented on README.md
> +    * [HTTP configuration customisation](#http-configuration-customisation)
Custom HttpClient

2022-03-10 13:42 UTC, RommeroInCountry commented on README.md
please see c#-doc changes in code

2022-03-10 13:42 UTC, RommeroInCountry commented on README.md
> +You can provide custom HTTP configuration though the `StorageConfig.HttpClient` option. It will be helpful for the configuring of network proxy, custom timeouts, specific socket configuration, and ot
You can provide your own HttpClient instance using the `StorageConfig.HttpClient` option. It can be helpful when  configuring a network proxy, custom timeouts, specific socket configuration, etc.

2022-03-10 13:42 UTC, RommeroInCountry commented on README.md
> +For a detailed example of custom HTTP configuration, please [check this resource](/InCountrySDK.Examples/NetworkProxyExample.cs).
For a detailed example of HttpClient customisation, please

2022-03-10 13:42 UTC, RommeroInCountry commented on README.md
> +Another way to change default behaviour of the InCountry Storage instance is inheritance from `Storage` class.
No need to do it here. I'd remove this one and add this line in Release notes (not exactly this one, but changed a bit)

We can add the following line in Storage configuration section after the code example:
"You can further extend the configuration and behaviour of the InCountry Storage instance by inheriting from the `Storage` class"

2022-03-10 13:42 UTC, RommeroInCountry commented on InCountrySDK/Resources.resx
> +    <value>HTTP timeout configuration must be configured during the external HTTP client initialisation</value>
HTTP timeout configuration is mutually exclusive with custom HttpClient.

2022-03-10 13:42 UTC, RommeroInCountry commented on InCountrySDK/Storage.cs
> +        /// An empty constructor for the usage in inherited classes
An empty constructor to use for class inheritance

2022-03-10 13:42 UTC, RommeroInCountry commented on InCountrySDK/Storage.cs
> +        /// A protected constructor for the overriding in inherited classes
A protected constructor to override in the ...

2022-03-10 15:30 UTC, RommeroInCountry approved these changes

2022-03-11 11:32 UTC, robert-par approved these changes

2022-03-11 11:58 UTC, merged