SDK-349 [C# SDK] Remove API Key authorization support
incountry/sdk-csharp pull request #82
Opened 2021-05-12 12:42 UTC by VladimirLevitskiy

Please read this for our PR Culture:
------------------------------------
https://incountry.atlassian.net/wiki/spaces/ED/pages/46858869/Pull+requests+culture

Work relates to:
----------------
Link(s) to Jira Task/User Story/Bug/Epic:
- [SDK-349](https://incountry.atlassian.net/browse/SDK-349)

Code Quality (Before submitting PR)
------------
- [ ] Ensure code compiles and passes Sonar Lint.
- [ ] Do your best to ensure integration tests pass. If they don't then...
- [ ] Remove, ignore, or mark pending any brittle tests.
- [ ] Remove commented out code.

Target Release
--------------
- [ ] Please put the target release vehicle this needs to be bundled with.
- [ ] Did you increment the version? What is the new version?

2021-05-26 11:57 UTC, RommeroInCountry requested changes

2021-05-26 11:57 UTC, RommeroInCountry commented on UnitTests/HttpDaoTest.cs
> +            using var httpDao = HttpDao.NewDao("envId", new ExternalTokenClient(() => "token"),
Let's call it StaticTokenClient - this would be a better naming. Kudos to @artemgolozubov for introducing it :D

2021-05-26 12:43 UTC, VladimirLevitskiy commented on UnitTests/HttpDaoTest.cs
> +            using var httpDao = HttpDao.NewDao("envId", new ExternalTokenClient(() => "token"),
We decide to leave current naming

2021-05-26 12:56 UTC, RommeroInCountry approved these changes

2021-05-27 15:45 UTC, RommeroInCountry approved these changes

2021-05-28 07:29 UTC, robert-par approved these changes

2021-05-28 07:30 UTC, merged