SDK-385 [C# SDK] write and batchWrite should return data from PoPAPI response
incountry/sdk-csharp pull request #87
Opened 2021-06-03 15:19 UTC by VladimirLevitskiy

Please read this for our PR Culture:
------------------------------------
https://incountry.atlassian.net/wiki/spaces/ED/pages/46858869/Pull+requests+culture

Work relates to:
----------------
Link(s) to Jira Task/User Story/Bug/Epic:
- [SDK-385](https://incountry.atlassian.net/browse/SDK-385)

Code Quality (Before submitting PR)
------------
- [ ] Ensure code compiles and passes Sonar Lint.
- [ ] Do your best to ensure integration tests pass. If they don't then...
- [ ] Remove, ignore, or mark pending any brittle tests.
- [ ] Remove commented out code.

Target Release
--------------
- [ ] Please put the target release vehicle this needs to be bundled with.
- [ ] Did you increment the version? What is the new version?

2021-07-06 13:42 UTC, robert-par approved these changes

2021-07-07 13:40 UTC, RommeroInCountry requested changes

2021-07-07 13:40 UTC, RommeroInCountry commented on InCountrySDK/Storage.cs
> +            var recorderRecord = _transformer.GetRecord(recordedTransferRecord);
i'd propose recorderRecord -> receivedRecord

2021-07-07 14:05 UTC, RommeroInCountry approved these changes

2021-07-07 14:20 UTC, artemgolozubov approved these changes

2021-07-07 14:55 UTC, merged