SDK-432 [C# SDK] refactor README
incountry/sdk-csharp pull request #99
Opened 2021-08-25 17:08 UTC by VladimirLevitskiy

Work relates to:
----------------
Link(s) to Jira Task/User Story/Bug/Epic (if any):
- [SDK-432](https://incountry.atlassian.net/browse/SDK-432)

Code Quality (Before submitting PR)
------------
- [x] Ensure code compiles and passes Sonar Lint.
- [x] Do your best to ensure integration tests pass. If they don't then...
- [x] Remove, ignore, or mark pending any brittle tests.
- [x] Remove commented out code.

Target Release
--------------
- [ ] Please put the target release vehicle this needs to be bundled with.
- [ ] Did you increment the version? What is the new version?

2021-08-30 15:06 UTC, RommeroInCountry requested changes

2021-08-30 15:06 UTC, RommeroInCountry commented on README.md
> +The C# SDK supports a capability to provide custom encryption/decryption methods if you decide to use your own algorithm instead of the default one.
The C# SDK allows to provide custom ...

2021-08-30 15:06 UTC, RommeroInCountry commented on README.md
> +The name parameter of the `AbstractCipher` constructor is used to differentiate custom encryptions from each other and from the default encryption as well. This way the SDK is able to successfully de
The `name` parameter

2021-08-30 15:06 UTC, RommeroInCountry commented on README.md
> +The name parameter of the `AbstractCipher` constructor is used to differentiate custom encryptions from each other and from the default encryption as well. This way the SDK is able to successfully de
to differentiate custom encryption implementations from each other

2021-08-31 17:23 UTC, VladimirLevitskiy commented on InCountrySDK/IStorage.cs
> +        /// Performs an asynchronous batch key rotation migration of records
latest

2021-08-31 18:18 UTC, VladimirLevitskiy commented on README.md
> +The C# SDK supports a capability to provide custom encryption/decryption methods if you decide to use your own algorithm instead of the default one.
allows providing

2021-09-01 16:26 UTC, RommeroInCountry approved these changes

2021-09-01 16:39 UTC, RommeroInCountry approved these changes

2021-09-02 11:02 UTC, RommeroInCountry approved these changes

2021-09-02 11:17 UTC, merged